# To modify this file, make sure you only modify the values between ":" and "#"
# for each key: value pair.
# The # indicates the start of a comment

# Connection configuration
# playerlimit: the server player limit, if reached, further players will be turned away
# port: port that the players connect through (it must be open/forwarded for them to be able to connect)
# timeout: timeout for automatic client disconnection in seconds (keep above 60)
# local: if only people in the host machine should be able to connect (i.e. you), ideal if testing setup
# show_ms2-prober: log ms2-prober connections in the server log, which will happen regularly if your server is public


playerlimit: 100
port: 50000
timeout: 250
local: false
show_ms2-prober: true

# Master server advertisement configuration
# use_masterserver: if server should be listed on the master server list
# masterserver_name: the name of the server, and what will be shown on the master sever list
# masterserver_description: the description of the server, listed on the server select screen
# masterserver_ip: the AO master server IP (do not modify)
# masterserver_port: the AO master server port (do not modify)

use_masterserver: true
masterserver_name: My First DR Server
masterserver_description: This is my flashy new DR server
masterserver_ip: master.aceattorneyonline.com # Keep
masterserver_port: 27016 # Keep

# Passwords for different roles
# modpass: password for moderators
# cmpass: password for community managers
# gmpass: password for game masters
# gmpass1: password for game masters that is only good for Monday based on server time
# gmpass2: password for game masters that is only good for Tuesday based on server time
# ....

modpass: Mod
cmpass: Community Manager

gmpass: Universal
gmpass1: Monday
gmpass2: Tuesday
gmpass3: Wednesday
gmpass4: Thursday
gmpass5: Friday
gmpass6: Saturday
gmpass7: Sunday

# OOC configurations
# motd: message sent to OOC on connection
# hostname: 'username' of the server (precedes all OOC messages sent by the server)
# discord_link: Discord invite link for the server, accessible through /discord

motd: Welcome to my server!
hostname: <dollar>H
discord_link: None

# Roll configurations

max_numdice: 20
max_numfaces: 11037
max_modifier_length: 12
max_acceptable_term: 22074
def_numdice: 1
def_numfaces: 6
def_modifier: ''
        
# RP configurations
# rp_mode_enabled: if RP mode should be enabled (restricts certain commands)
# blackout_background: background to display if lights are turned off/player is blinded
# default_area_description: description to show with /look if no description is set
# party_lights_timeout: time a party needs to be in an area with no lights to automatically disband
# showname_max_length: maximum length of a custom showname
# sneak_handicap: automatic handicap to impose players who start sneaking
# spectator_name: name spectators get in /getarea(s)

rp_mode_enabled: true
blackout_background: Blackout_HD
default_area_description: No description.
party_lights_timeout: 10
showname_max_length: 30
sneak_handicap: 5
spectator_name: SPECTATOR

# Music flood configuration
# This checks if one player played "times_per_interval" tracks within "interval_length" seconds
# and if so, it prevents them from playing any further tracks for "mute_length" seconds

music_change_floodguard:
  times_per_interval: 3
  interval_length: 20
  mute_length: 10

# Currently unused
# Changing them will do nothing

use_district: false
district_ip: 127.0.0.1
district_port: 11037
district_password: enter_password
announce_areas: true
debug: false
guardpass: Guard
help_msg: TODO